# test1 sample: Numpy

`import nupy as np`でnumpyパッケージをインポート

In [1]:
import numpy as np


In [2]:
sampleArray = np.arange(15).reshape(3, 5)
print("sample array", sampleArray)

sample array [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
type(sampleArray)

numpy.ndarray

`shape`は多次元配列の形(各次元の要素数)を取得

In [4]:
sampleArray.shape

(3, 5)

`ndim`は次元を取得

In [5]:
sampleArray.ndim

2

`dtype`で型を取得

In [6]:
sampleArray.dtype

dtype('int64')

`itemsize` で要素1個のバイト長を取得

In [8]:
sampleArray.itemsize

8

`size` で全体の要素数を取得

In [7]:
sampleArray.size

15

`array` でpython配列から配列生成。

In [9]:
np.array([3, 5, 6])

array([3, 5, 6])

In [ ]:
np.array([3, 5, 6]).dtype

dtype('int32')

型は自動的に決定される

In [10]:
np.array([2, 3.2, 4.3])

array([2. , 3.2, 4.3])

In [11]:
np.array([2, 3.2, 4.3]).dtype

dtype('float64')

明示的な型指定も可能

In [12]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

引数はタプルでもよい

In [13]:
np.array((4, 5, 3))

array([4, 5, 3])

多次元配列もサポート

In [14]:
np.array([[1, 2, 3], [4, 5, 6] ])

array([[1, 2, 3],
       [4, 5, 6]])

複素数配列も作れる

In [16]:
np.array([2, 4, 6, 2], dtype="complex")

array([2.+0.j, 4.+0.j, 6.+0.j, 2.+0.j])

zerosで0に初期化した配列、onesで1に初期化した配列、emptyで未初期化(値が不定)の配列が作れる

In [17]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.empty((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

arangeは開始、終了、ステップを指定して配列作成。終了値は含まない。

In [20]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])